### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by onebadpanda** [fm4d/KickassAPI#9] opened 2015-02-20 03:09 UTC
Attempted the example shown on the main page:
```python
from KickassAPI import Search, Latest, CATEGORY, ORDER

#Print the basic info about first 25 results of "Game of thrones" search
for t in Search("Game of thrones"):
    t.lookup()
```

and saw the following
```python
Traceback (most recent call last):
  File "/sample.py", line 6, in <module>
    for t in Search("Game of thrones"):
  File "/virtualenvs/sample/lib/python2.7/site-packages/KickassAPI.py", line 329, in __init__
    self.url = SearchUrl(query, page, category, order)
  File "/virtualenvs/sample/lib/python2.7/site-packages/KickassAPI.py", line 140, in __init__
    self.build()
  File "/virtualenvs/sample/lib/python2.7/site-packages/KickassAPI.py", line 162, in build
    self.max_page = self._get_max_page(ret)
  File "/virtualenvs/sample/lib/python2.7/site-packages/KickassAPI.py", line 91, in _get_max_page
    tds = int(pq("h2").text().split()[-1])
IndexError: list index out of range
```

**Comment by fm4d** [comment] 2015-02-20 08:53
PyPI package is unfortunately outdated at the moment, this error ( caused by gzip ) is fixed in current version. Ill try to update PyPI package as soon as possible.

**Closed by fm4d** 2015-02-20 08:53 UTC
